from types import SimpleNamespace

from cvmax.db import MemoryDB
from cvmax.jobs.models import Vacancy
from cvmax.learning import market
from cvmax.learning.market import (
    PostingSkills, SkillExtraction, aggregate, extract_skills, normalise_skill, render_market,
)
from cvmax.llm import LLMError
from scripts.learn_market import run_market
from scripts.snapshot_jobs import run_snapshot


def test_normalise_skill():
    assert normalise_skill("  MS Excel ") == "excel"
    assert normalise_skill("PostgreSQL") == "sql"
    assert normalise_skill("Power-BI") == "power bi"
    assert normalise_skill("English  C1") == "english"
    assert normalise_skill("C++.") == "c++"
    assert normalise_skill("x" * 41) == ""
    assert normalise_skill("  ..  ") == ""


def test_aggregate_shares_and_top():
    by_id = {str(i): {"sql", "excel"} if i < 5 else {"python"} for i in range(10)}
    by_id["x"] = {"rare"}
    rows = aggregate(by_id, 100, min_share=0.03)
    assert [r["skill"] for r in rows] == ["excel", "python", "sql"]  # 5 levels: alphabetical; rare = 1% < 3%
    assert rows[0] == {"skill": "excel", "postings": 5, "total_postings": 100, "share": 0.05}
    many = {str(i): {f"s{j}" for j in range(30)} for i in range(10)}
    assert len(aggregate(many, 10, top=20)) == 20


class FakeLLM:
    def __init__(self, fail_call=None, fail_calls=()):
        self.calls, self.fail_call, self.fail_calls = [], fail_call, set(fail_calls)

    def ask(self, *, system, content, output_model, effort):
        self.calls.append(content[0]["text"])
        if self.fail_call == len(self.calls) or len(self.calls) in self.fail_calls:
            raise LLMError("boom")
        ids = [ln[3:] for ln in content[0]["text"].splitlines() if ln.startswith("id=")]
        return output_model(items=[PostingSkills(id=i, skills=["MS Excel", "SQL"]) for i in ids])


def test_extract_skills_batches_and_survives_error():
    postings = [{"id": str(i), "title": "Analyst", "company": "Acme", "snippet": "sql"} for i in range(60)]
    llm = FakeLLM(fail_call=2)
    out, covered = extract_skills(llm, postings, batch=25)
    assert len(llm.calls) == 3
    assert len(out) == 35  # 25 + 10, the middle batch skipped
    assert out["0"] == {"excel", "sql"}
    assert covered == {str(i) for i in range(60)} - {str(i) for i in range(25, 50)}


def test_extract_skills_empty_posting_is_covered():
    class EmptyLLM:
        def ask(self, *, system, content, output_model, effort):
            return output_model(items=[])

    out, covered = extract_skills(EmptyLLM(), [{"id": "a", "title": "t"}, {"id": "b", "title": "t"}])
    assert out == {} and covered == {"a", "b"}


def test_render_market_cap_and_content():
    rows = [{"skill": f"skill{i}", "postings": 50 - i, "total_postings": 100, "share": 0.5 - i / 100}
            for i in range(20)]
    text = render_market("law", {"UK": (100, rows), "EU": (0, [])}, 30, "2026-01-02")
    assert text.startswith("<!-- generated by scripts/learn_market.py on 2026-01-02 -->")
    assert "## What postings ask for right now (last 30 days)" in text
    assert "UK: 100 postings for legal intern" in text and "skill0 50%" in text
    assert "EU:" not in text
    huge = {f"R{i}": (100, rows) for i in range(30)}
    assert len(render_market("law", huge, 30, "2026-01-02")) <= market.RENDER_MAX_CHARS


def _vacs(n):
    return [Vacancy(url=f"https://example.com/{i}", title=f"Job {i}", company="Acme", location="Kyiv",
                    source="DOU", posted_at="2026-01-01", salary=None, snippet="sql", remote=False)
            for i in range(n)]


def test_run_snapshot_writes_rows_and_dry_run():
    db = MemoryDB()
    calls = []

    def search(q):
        calls.append(q)
        return SimpleNamespace(vacancies=_vacs(3), sources_ok=["DOU"], sources_failed=["Jooble"], deep_links=[])

    summary = run_snapshot(db, search, ["law"], ["UK"], sleep=0)
    assert len(calls) == len(market.ROLE_QUERIES["law"])
    assert calls[0].level == "Internship" and calls[0].region == "UK"
    assert summary == [{"program": "law", "region": "UK", "fetched": 12, "upserted": 12, "failed": 4}]
    row = db.vacancies[("https://example.com/0", market.ROLE_QUERIES["law"][-1], "UK")]  # MemoryDB key: (url, role_family, region)
    assert row["region"] == "UK" and row["role_family"] == market.ROLE_QUERIES["law"][-1]

    db2 = MemoryDB()
    run_snapshot(db2, search, ["law"], ["UK"], sleep=0, dry_run=True)
    assert db2.vacancies == {}


def test_run_snapshot_survives_search_error():
    def search(q):
        raise RuntimeError("down")

    summary = run_snapshot(MemoryDB(), search, ["other"], ["EU"], sleep=0)
    assert summary[0]["failed"] == 3 and summary[0]["fetched"] == 0


def test_run_market_writes_file_only_with_enough_postings(tmp_path):
    db = MemoryDB()
    rows = [{**v.to_row(), "region": "UK", "role_family": "legal intern", "query": "legal intern"}
            for v in _vacs(25)]
    rows += [{**v.to_row(), "url": v.url + "-p", "region": "UK", "role_family": "intern", "query": "intern"}
             for v in _vacs(5)]
    db.upsert_vacancies(rows)
    res = run_market(db, FakeLLM(), ["law", "other"], ["UK", "EU"], 30, "2026-01-02", tmp_path)
    assert (tmp_path / "law.md").exists() and not (tmp_path / "other.md").exists()
    assert res["written"] == [tmp_path / "law.md"]
    assert "excel 100%" in (tmp_path / "law.md").read_text()
    saved = db.skill_demand("law", "UK")
    assert {r["skill"] for r in saved} == {"excel", "sql"} and saved[0]["total_postings"] == 25
    assert db.skill_demand("other", "UK")  # data is stored for small directions too

    db2 = MemoryDB()
    db2.upsert_vacancies(rows)
    tmp2 = tmp_path / "dry"
    run_market(db2, FakeLLM(), ["law"], ["UK"], 30, "2026-01-02", tmp2, dry_run=True)
    assert not tmp2.exists() and db2.skill_demand("law", "UK") == []


def _law_db(n):
    db = MemoryDB()
    db.upsert_vacancies([{**v.to_row(), "region": "UK", "role_family": "legal intern", "query": "legal intern"}
                         for v in _vacs(n)])
    return db


def test_run_market_half_batches_failed_skips_region(tmp_path, capsys):
    db = _law_db(100)  # 4 batches of 25
    llm = FakeLLM(fail_calls={2, 4})
    res = run_market(db, llm, ["law"], ["UK"], 30, "2026-01-02", tmp_path)
    assert len(llm.calls) == 4
    assert db.skill_demand("law", "UK") == [] and res["written"] == [] and not (tmp_path / "law.md").exists()
    assert "coverage 50%" in capsys.readouterr().out
    # the share is counted from the covered postings
    skills, covered = extract_skills(FakeLLM(fail_calls={2, 4}), [{"id": str(i), "title": "x"} for i in range(100)])
    assert len(covered) == 50 and aggregate(skills, len(covered))[0]["share"] == 1.0


def test_run_market_all_batches_failed_keeps_existing_file(tmp_path):
    db = _law_db(50)
    path = tmp_path / "law.md"
    path.write_text("old good content\n", encoding="utf-8")
    res = run_market(db, FakeLLM(fail_calls={1, 2}), ["law"], ["UK"], 30, "2026-01-02", tmp_path)
    assert res["written"] == [] and path.read_text(encoding="utf-8") == "old good content\n"
    assert db.skill_demand("law", "UK") == []
    run_market(db, FakeLLM(fail_calls={1, 2}), ["law"], ["UK"], 30, "2026-01-02", tmp_path / "fresh")
    assert not (tmp_path / "fresh").exists()


def test_run_market_one_of_ten_batches_failed_keeps_region(tmp_path):
    db = _law_db(250)  # 10 batches of 25
    res = run_market(db, FakeLLM(fail_calls={3}), ["law"], ["UK"], 30, "2026-01-02", tmp_path)
    saved = db.skill_demand("law", "UK")
    assert saved and all(r["total_postings"] == 225 and r["postings"] == 225 for r in saved)
    assert res["written"] == [tmp_path / "law.md"]
    assert res["by_program"]["law"]["UK"][0] == 225
    assert "UK: 225 postings" in (tmp_path / "law.md").read_text() and "excel 100%" in (tmp_path / "law.md").read_text()
